#!/bin/bash
# Air Quality Dashboard - Exact Run Steps

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   🚀 Air Quality Monitoring Dashboard - PRODUCTION READY       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

PROJECT_ROOT="/Users/arundathiasalla/Downloads/emg/emerge1"

echo "📋 EXACT STEPS TO RUN:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Ensure PostgreSQL is Running"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  brew services start postgresql@15"
echo ""
echo "  ✓ Verify: psql -U postgres -c \"SELECT 1;\""
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Start Backend Server (Terminal 1)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  cd $PROJECT_ROOT/backend"
echo "  npm start"
echo ""
echo "  Expected output:"
echo "    🚀 Backend API Server running on http://localhost:49217"
echo "    🔌 WebSocket Server running on ws://localhost:49218"
echo "    ⚠️  API_KEY not configured in .env"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Start Frontend Server (Terminal 2)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  cd $PROJECT_ROOT/frontend"
echo "  ./node_modules/.bin/vite --port 51783"
echo ""
echo "  Or use npm:"
echo "  npm run dev"
echo ""
echo "  Expected output:"
echo "    VITE v4.5.14 ready in 96 ms"
echo "    ➜  Local: http://localhost:51783/"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Open Dashboard in Browser"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  🌐 Navigate to: http://localhost:51783"
echo ""

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    🎯 QUICK TEST COMMANDS                      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Backend Health:"
echo "  curl http://localhost:49217/health"
echo ""
echo "Get Latest Data (empty until API key configured):"
echo "  curl http://localhost:49217/api/latest"
echo ""
echo "Get Device List:"
echo "  curl http://localhost:49217/api/devices"
echo ""
echo "Get Statistics:"
echo "  curl http://localhost:49217/api/stats"
echo ""

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                 🔑 TO ADD REAL SENSOR DATA                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "1. Edit: $PROJECT_ROOT/backend/.env"
echo ""
echo "2. Set real API credentials:"
echo "   API_KEY=your_api_key_here"
echo "   API_URL=https://your-api-endpoint.com"
echo ""
echo "3. Restart backend:"
echo "   Ctrl+C in backend terminal, then: npm start"
echo ""
echo "4. Dashboard will auto-populate with live data"
echo ""

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                      ✅ WHAT YOU GET                           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✓ Health Impact Score (0-100) with color indicators"
echo "✓ Sensor value breakdown bars"
echo "✓ Interactive Leaflet map with locations"
echo "✓ PM2.5 and temperature trend charts"
echo "✓ Smart alert notifications"
echo "✓ Daily report with peak pollution times"
echo "✓ Real-time WebSocket updates"
echo "✓ PostgreSQL data persistence"
echo ""

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                      🎯 PROJECT STATUS                         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Backend: READY (port 49217)"
echo "✅ Frontend: READY (port 51783)"
echo "✅ WebSocket: READY (port 49218)"
echo "✅ Database: READY (PostgreSQL)"
echo "✅ All Features: IMPLEMENTED"
echo "✅ No Mock Data: CONFIGURED"
echo ""
echo "Status: 🚀 PRODUCTION READY - OPEN http://localhost:51783"
echo ""
